AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  sam-demo

Globals:
  Function:
    Timeout: 100

    LoggingConfig:
      LogFormat: JSON
Resources:
  ChatFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: sam_tutorial_demo/
      Handler: app.lambda_handler
      Runtime: python3.11
      Architectures:
      - x86_64
